Use env vars for DB settings
cutwater/ansible-events-ui pull request #1
Opened 2022-08-15 19:34 UTC by Red-HAP

## Description

This branch adds configuration parameters for the database with values taken from a `.env` file which **must** be sourced before launching the local database.

These are updates to `cutwater/misc/pg_stat_statements`

2022-08-16 14:51 UTC, Alex-Izquierdo requested changes
When I proposed to move all those configurations to the .env file, I didn't mean add the .env to the repository. 
.env file is precisely to customize the environment and It should not be added to the repository. In fact, it should be added to the .gitignore. 

You could add something like `.env.sample`
Also I think the docs should speak about it. 

What I propose is defining all those configurations in the docker-compose through environment variables with default values. E.g:

```yaml
    volumes:
      - "./postgres/initdb.d:/docker-entrypoint-initdb.d"
      - "postgres_data:/var/lib/postgresql/data"
    environment:
      - PG_MAX_CONNECTIONS=${PG_MAX_CONNECTIONS:-1000}
    command: ->
      postgres -c max_connections=${PG_MAX_CONNECTIONS}
 ```
 
 So, If I want to customize it, I can create a .env file without modify any versioned file. like:
 ```
 PG_MAX_CONNECTIONS=2000
 ```

Also, to keep the compose definition more readable and compact, I suggest use the following syntax:
```yaml
    command: ->
      postgres 
      -c ssl=${PG_SSL}
      -c ssl_cert_file=${PG_SSL_CERT_FILE}
      -c ssl_key_file=${PG_SSL_KEY_FILE}
# etc...
```

2022-08-16 14:51 UTC, Alex-Izquierdo commented on .env
> +export PG_MAX_CONNECTIONS=1000
.env doesn't support "export" keyword

2022-08-17 15:04 UTC, cutwater requested changes
@Red-HAP Thank you for all your effort working on this change. I really like how you documented the database options and fine tuning that may be required. I have a few questions left, can you please take a look?

2022-08-17 17:06 UTC, Red-HAP commented on tools/docker/postgres/initdb.d/uuid-ossp.sql
> +CREATE EXTENSION "uuid-ossp";
I can take it out, but, from my memory, I thought you and I were talking about using uuid_generate_v4() for primary keys.

If I was mistaken, or if this is too much scope-creep, then I'll take it out.

2022-08-17 17:09 UTC, cutwater commented on tools/docker/postgres/initdb.d/uuid-ossp.sql
> +CREATE EXTENSION "uuid-ossp";
At the moment the only place where UUIDs are generated as primary keys is `user` table, and it generates them on a python side.

2022-08-17 17:10 UTC, cutwater commented on tools/docker/postgres/initdb.d/uuid-ossp.sql
> +CREATE EXTENSION "uuid-ossp";
When there is a need for `uuid-ossp` occurs, we can add it in migration.

2022-08-17 17:11 UTC, Red-HAP commented on README-POSTGRES.md
> +| logging_collector | **on** | off | Activate (on) or deactivate (off) the logging collector. The logging collector captures stderr logging and writes the data to rotated log files in the `${PGDATA}/
This is probably a holdover from working with platforms like AWS. I can take it out... but the question I have is: How much does docker/podman retain from stderr logging? The advantage I can see is that the rotated log files could possible retain more data. If the docker log retention is acceptible, I can take this out.

Thoughts?

2022-08-17 17:48 UTC, cutwater commented on README-POSTGRES.md
> +| logging_collector | **on** | off | Activate (on) or deactivate (off) the logging collector. The logging collector captures stderr logging and writes the data to rotated log files in the `${PGDATA}/
AFAIK docker keeps logs indefinitely for a container _by default_. So as long as a container exists, logs are stored too.
Logging driver and options can be customized though, but personally I've never had a need to do that in my local development environment.

2022-08-17 23:38 UTC, Red-HAP commented on tools/docker/postgres/initdb.d/uuid-ossp.sql
> +CREATE EXTENSION "uuid-ossp";
Removed.

2022-08-17 23:39 UTC, Red-HAP commented on tools/docker/postgres/postgresql.conf
> +include_dir = '/etc/postgresql/conf.d'			# include files ending in '.conf' from
Verified and done.

2022-08-17 23:41 UTC, Red-HAP commented on README-POSTGRES.md
> +| logging_collector | **on** | off | Activate (on) or deactivate (off) the logging collector. The logging collector captures stderr logging and writes the data to rotated log files in the `${PGDATA}/
logging_collector has been reset to off

2022-08-17 23:41 UTC, Red-HAP commented on README-POSTGRES.md
> +| log_min_duration_statement | **2000** | -1 | -1 disables; 0 logs all statements; >0 logs statements executing longer than the specified value (in milliseconds). This is set to log any statement tha
Set to 1000

2022-08-18 14:46 UTC, cutwater approved these changes

2022-08-18 14:46 UTC, merged